[build-system]
requires = [
  "setuptools >= 61.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "gori-py-utils"
version = "0.0.0"
authors = [
  { name="RedReservoir", email="gerard.ortega88@gmail.com" },
]
description = "Miscellaneous Python utilities for gori projects"
